spring.application.name=back

spring.datasource.url=${DATABASE_BACK_URL}
spring.datasource.username=${DATABASE_BACK_USERNAME}
spring.datasource.password=${DATABASE_BACK_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace = never

api.infra.security.secret = ${JWT_SECRET}
